In [12]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

### Data types and variables ###
age = 20
name = "John"
single = True

# Variable manipulation
ageDays = age * 365

# Lists
numList = [1, 2, 3, 3.5] # numeric list (integers/floats)
strList = ["1", "2", "3", "4"] # string list
logList = [True, True, False, True] # Boolean list
mixedList = [True, 1, "2"]

# Averaging a list
import numpy as np  # np is the conventional name
np.mean(numList)

2.375

In [13]:
### Arrays ###
import numpy as np

myMatrix = np.array([[1, 2, 3], [4, 5, 6]])
print(myMatrix)

# Access the first row
print(myMatrix[0]) # note that the first item in Python
      # is listed as position 0 rather than position 1)        

# Access the second column
print(myMatrix[:,1])

[[1 2 3]
 [4 5 6]]
[1 2 3]
[2 5]


In [14]:
### Dataframes ###
import pandas as pd # again, ‘pd’ is the convention
my_DF = pd.DataFrame([[1, "a", "A"], [2, "b", "B"], 
                      [3, "c", "C"], [4, "d", "D"], 
                      [5, "e", "E"]], columns=["c1", "c2", "c3"])

print(my_DF.dtypes) # print data types

# Change data types
my_DF["c1"] = my_DF["c1"].astype(str)
print(my_DF.dtypes) # print data types

# Access part of a dataframe
my_DF.iloc[0] # read the first row, all columns
my_DF.ix[2] # read the third column, all rows
my_DF.iloc[0,2] # read cell in row 1, column 3

c1     int64
c2    object
c3    object
dtype: object
c1    object
c2    object
c3    object
dtype: object


'A'